name: Update PubMed CSV

on:
  schedule:
    - cron: "0 12 * * *"   # every day at 12:00 UTC
  workflow_dispatch:        # manual trigger

permissions:
  contents: write

jobs:
  update-pubmed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python pubmed_update.py

      - name: Commit & Push results
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add pubmed_results.csv
          git commit -m "Update PubMed results $(date -u)" || echo "No changes to commit"
          git push
